### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by curlyfro** [jaredmahan/odata-query-builder#1]
import { QueryBuilder } from "odata-query-builder";

does not work

**Comment by connorjohnmelnick** [comment]
`"files": [ "./src/queryBuilder.ts" ],`

Adding this config to your tsconfig.json file should fix this issue.  I can submit a PR if this project is still being maintained.  However, I think there are more issues than just this one that is blocking

**Comment by jaredmahan** [comment]
Looking into this now.

**Comment by jaredmahan** [comment]
```
import { QueryBuilder } from "odata-query-builder";

const test = new `QueryBuilder().count();
```

After running npm install, the following should work.  What kind of error are you seeing?

**Comment by jaredmahan** [comment]
I fixed an issue where the package was ignoring the dist directory. You should be good to try this again if you wish. Also, the code base has been updated.
